working_dir: &working_dir ~/app
version: 2.1
jobs:
  red:
    ###############################
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: a
          
          command: |
            python orb.py
            
            
  blue:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: b
          
          command: |
            python orb.py
  silver:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: q
          
          command: |
            python orb.py

  yellow:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: w
          
          command: |
            python orb.py
  green:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: e
          
          command: |
            python orb.py

  purple:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: r
          
          command: |
            python orb.py

  pink:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      - run:
          name: t
          
          command: |
            python orb.py

  black:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: y
          
          command: |
            python orb.py
  white:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: u
          
          command: |
            python orb.py


  grey:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: i
          
          command: |
            python orb.py


workflows:
    version: 2.1
    build:
        jobs:
             - red
             - blue
             - silver
             - yellow
             - green
             - purple
             - pink
             - black
             - white
             - grey
